version: "3."

services:
  api:
    build:
      context: ./services
    command: uvicorn services.api_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  scraping:
    build:
      context: ./services
    command: uvicorn services.scraping_service:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  retriever:
    build:
      context: ./services
    command: uvicorn services.retriever_service:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"

  language:
    build:
      context: ./services
    command: uvicorn services.language_service:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"

  voice:
    build:
      context: ./services
    command: uvicorn services.voice_service:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"

  orchestrator:
    build:
      context: ./services
    command: uvicorn services.orchestrator_service:app --host 0.0.0.0 --port 8006
    ports:
      - "8006:8006"
